print "I am a hacker, yes I am!"
print "Born to spam and born to scam!"
print "Open my emails, naive lambs."
print "They contain such neat programs,"
print "Perhaps a virus, worm or bot."
print "Open my emails, but beware."
print "My malware is your nightmare!"